name: GitHub Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          dir

  SonarQube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Especifica la versión de Java que quieres usar
          distribution: 'adopt'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.php') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Download SonarQube Scanner
        run: |
          Invoke-WebRequest -Uri 'https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.0.2311/sonar-scanner-cli-4.6.0.2311-windows.zip' -OutFile 'sonar-scanner-cli.zip'
          Expand-Archive -Path 'sonar-scanner-cli.zip' -DestinationPath 'sonar-scanner'
      
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          .\sonar-scanner\bin\sonar-scanner.bat ^
            -Dsonar.projectKey=Restaurante_Laravel ^
            -Dsonar.sources=. ^
            -Dsonar.exclusions=vendor/**,node_modules/** ^
            -Dsonar.language=php ^
            -Dsonar.php.laravel=TRUE ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
